#!/bin/bash
##SBATCH -p medium
##SBATCH -t 10:00:00
##SBATCH -N 4
##SBATCH -c 24

sabre pe -c -f /usr/users/aiyesa/geno_fastq_data/fastq/2023_data/M005083-Plate8_S136_L003_R1_001.fastq.gz \
-r /usr/users/aiyesa/geno_fastq_data/fastq/2023_data/M005083-Plate8_S136_L003_R2_001.fastq.gz \
-b /usr/users/aiyesa/geno_fastq_data/fastq/2023_data/first_bcode.txt \
-u /usr/users/aiyesa/geno_fastq_data/fastq/2023_data/demultiplexed_2023_samples/unknown_barcode8f_1_32.fastq \
-w /usr/users/aiyesa/geno_fastq_data/fastq/2023_data/demultiplexed_2023_samples/unknown_barcode8r_1_32.fastq

